### ISSUE TITLE
Gpipe Benchmark

### ISSUE THREAD

**Issue by vibhatha** [kakaobrain/torchgpipe#10]
I want to compare gpipe benchmark to torchgpipe benchmark. I ran some micro benchmarks. I want to test same overheads in Gpipe. Is that script opensource?

**Comment by sublee** [comment]
I don't understand what do you need. Could you explain it in more detail?

**Comment by vibhatha** [comment]
@sublee 
What I mean is, there are scripts to benchmark TorchGpipe tool. I ran them and I get similar results as you say. I was wandering whether I can check it with your Gpipe original results. 

I couldn't find that script to replicate or approximately get Huang et al results and compare it with TorchGpipe results? 

Is this clear?

**Comment by sublee** [comment]
Thanks for explaining. The original implementation can be found in [Lingvo](https://github.com/tensorflow/lingvo/blob/master/lingvo/core/gpipe.py) but the benchmark scripts seem never to be published. We didn't create our own benchmark scripts for the original results. Instead, we just copied the numbers from the paper.

**Comment by vibhatha** [comment]
So, did you use the same hardware that they used?

**Comment by sublee** [comment]
We have run torchgpipe on NVIDIA Tesla P40 or V100 GPUs while P100 was used in the original experiment. For TPUs, torchgpipe does not support them.

**Comment by vibhatha** [comment]
I understand. 

One more thing to clarify. For the backward pass, in the torchgpipe implementation, 

Do you try to do the same thing done in the Google paper? 
Does microbatches used in the backward pass as well? 
Or done for the whole mini-batch?

**Comment by sublee** [comment]
Micro-batches work on both forward and backward pass. If you profile with NVIDIA Nsight Systems, you will see the typical pipeline parallelism timeline in both ways.

**Comment by vibhatha** [comment]
Did you try to replicate the timeline? I see unet-timeline benchmark folder?
Was that tried there?

**Comment by sublee** [comment]
I understood you're asking whether the timeline benchmark can be found in the original paper or not. Do I understand correctly? If so, we created the timeline benchmark on U-Net to show our efficiency on a model including skip connections. It was not derived from the original paper.

**Comment by vibhatha** [comment]
That is nice. I added some micro-benchmarks on the performance. I can create a PR once I make the code neat. I would like to contribute that to the code base if it is possible and the code is suitable. 

Thanks a lot for your support.

**Comment by sublee** [comment]
Contributions are welcomed. Please see [our contributing guide](https://github.com/kakaobrain/torchgpipe/blob/master/CONTRIBUTING.md) to refine your work to be suitable for torchgpipe. We would discuss new benchmarks on PR in the future. I think that it's time to close this issue.
