### ISSUE TITLE
Why does `Copy` compute gradients in reversed order

### ISSUE THREAD

**Issue by MlWoo** [kakaobrain/torchgpipe#15]
Niiiice work! I am confused that why `Copy` compute is in reversed order. 
https://github.com/kakaobrain/torchgpipe/blob/fca5d65fb68edddf1b056443d014c3aa7f416431/torchgpipe/copy.py#L59-L71

If I write the part, maybe it is implemented directly.
```python
 grad_input:List[Tensor] = []
 input_stream = current_stream(get_device(prev_stream)) 
  
 with use_stream(prev_stream), use_stream(next_stream): 
     for x in grad_output: 
         y = x.to(get_device(prev_stream)) 
         grad_input.append(y) 
  
         # 'next_stream' is not where 'x' has been allocated. 
         record_stream(x, next_stream) 
         # 'y' has been allocated on 'prev_stream'. 
         # It might be used on the current stream captured as 'input_stream'. 
         record_stream(y, input_stream) 
```
Is there something I do not take into account?  Could you explain it? Thank you very much.

**Comment by sublee** [comment]
Hi @MlWoo, that's a good question. Due to the absence of any comment on the `reversed()`, the behavior may look confusing. Typically, the CUDA timeline in forward and backward is symmetric with each other. `Copy` includes multiple copies and every single copy is visible as a `cudaMemcpyAsync` kernel in the CUDA timeline. To arrange the CUDA timeline consistently, we reverse the ordering of `cudaMemcpyAsync` kernels in backward.

**Comment by MlWoo** [comment]
@sublee Thank you very much. Does consistent CUDA timeline help improve computation efficiency? I am not familiar with CUDA. [The example of `torch.autograd.Function`](https://pytorch.org/docs/stable/notes/extending.html) provided by official site is also involved many operations of tensors which takes position of timeline.  But is seems that the author does not take notice of its order. Is the CUDA steam sensitive to `cudaMemcpyAsync` which occurs among with different devices? Maybe it is a stupid question.

**Comment by sublee** [comment]
Considered ordering of kernels on different CUDA streams might improve computational efficiency in some cases. However, a `Copy` invokes every `cudaMemcpyAsync` kernel on the same CUDA stream pair `prev_stream` and `next_stream`. So we can roughly think the reversed ordering in `Copy` does not affect the efficiency.

**Comment by MlWoo** [comment]
@sublee I still do not figure out what's the advantage of consistent CUDA timeline. The `Copy` still operates with same CUDA stream pair if implemented in normal order.

**Comment by sublee** [comment]
Sorry to confuse you.

I've usually inspected a CUDA timeline to improve computational performance. The readability of CUDA timeline is important to my use case. When every kernel is ordered consistently, I can easily assume that the forward and backward timeline is symmetric with each other. There is no other big advantage of consistent ordering but also, I think, there is no reason to order kernels inconsistently.

**Comment by MlWoo** [comment]
@sublee  Thanks a lot. I will close the issue.
