### ISSUE TITLE
Dual-license as BSD3 for PyTorch integration

### ISSUE THREAD

**Issue by pritamdamania87** [kakaobrain/torchgpipe#20]
The PyTorch team is currently evaluating pulling in fairscale's pipelining framework (https://github.com/facebookresearch/fairscale/tree/master/fairscale/nn/pipe) into PyTorch. Fairscale's pipeline framework is a fork of torchgpipe and to cleanly integrate this into PyTorch, the easiest option for us would be if torchgpipe is dual-licensed as BSD3 in addition to the Apache license.

Please let us know if this is feasible for the torchgpipe project since it would be a great addition to PyTorch core. We plan to add appropriate citations and acknowledgements to the original torchgpipe paper and project as part of this addition.

For more context, I have a PR on the PyTorch repo pulling in some of this work: https://github.com/pytorch/pytorch/pull/44090.

**Comment by chiheonk** [comment]
Hi @pritamdamania87 , 

Thanks for your interest in our project :) I personally am excited for torchgpipe's integration into PyTorch (if it happens).
We will discuss whether it is feasible to change the license to BSD3 or dual with it and get back to you soon.

**Comment by soumith** [comment]
hey, wanted to second the excitement.

It's also important to recognize and acknowledge contributions. So, from the PyTorch side, we will commit to adding in the release notes (cc: @pritamdamania87 @mrshenli )  that the code was forked from kakaobrain/torchgpipe and recognize your efforts. If you would like additional ways of acknowledgement, happy to help with that as well.

**Comment by pritamdamania87** [comment]
Hi @chiheonk, I'm happy to see there's a lot of interest on your end as well to integrate this into PyTorch :) Just wanted to check in to see if you have any updates on your end regarding licensing that you could share. This would help us in kicking off some of the work on our end.

Thanks for looking into this!

**Comment by sublee** [comment]
@pritamdamania87 We've just released v0.0.7, which accepts BSD-3-Clause as the only license. The implementation of v0.0.7 is identical to v0.0.6. I'm happy to help you making torchgpipe become a part of PyTorch.

**Comment by soumith** [comment]
thanks so much @sublee , great news.

**Comment by pritamdamania87** [comment]
Thanks a lot @sublee and @chiheonk, this is great! I'll let you know if I need any assistance.

**Comment by chiheonk** [comment]
We are closing this issue as it seems that fairscale.nn.Pipe is pulled into PyTorch (https://github.com/pytorch/pytorch/pull/44090).
