### ISSUE TITLE
About the debugger for running torchgpipe

### ISSUE THREAD

**Issue by Real-ZeminJiang** [kakaobrain/torchgpipe#26]
Hey authors @sublee @ummae @kimdwkimdw @huntrax11 @ildoonet :

I am wondering how to debug the async pytorch in the pipeline.py. There should be some proper debugger that can trace all the code both for CPU and GPU. Thank you very much for the help!

**Comment by Real-ZeminJiang** [comment]
And when I trying to step into 
```
            output = model(input)
```
inside main.py,

The program just stuck there and have no response for a long time. Can anyone give me some advice? Thank you very much!

**Comment by sublee** [comment]
This question does not seem to be related to torchgpipe. However, when I develop torchgpipe, NVIDIA Nsight Systems which is a GPU profiler was very useful to me.

To advise the program in stuck, I need more context. Which `main.py` did you run? Which GPUs do you use? Was any GPU utilized?

**Comment by sublee** [comment]
I close this issue because it's not related to torchgpipe and there's no response for a long while.
