### ISSUE TITLE
Could torchgpipe run on CPU-only machines? 

### ISSUE THREAD

**Issue by HuYang719** [kakaobrain/torchgpipe#29]
Dear torchgpipe team,

Thanks for sharing the code! I wonder could torchgpipe is suitable for the CPU-only machine/machines? Or any other possible method to deploy it on CPU-only environments? Thanks!

**Comment by sublee** [comment]
Do you just want to run torchgpipe-based code on CPU-only environments without performance benefit from pipeline parallelism? Then you can specify `'cpu'` or `['cpu', 'cpu', ...]` for `devices` option of `GPipe`. Despite torchgpipe cannot boost model performance without GPUs, this behavior is useful to unit test torchgpipe itself.

https://github.com/kakaobrain/torchgpipe/blob/a1b4ee25574864e7650e7905a69ce156da9752ec/tests/test_gpipe.py#L42-L59

**Comment by HuYang719** [comment]
Thank you very much for this reply, and want to double-check this is not for the CPU-only environment for multiple machines, right? I can only run the script mentioned in the CPU-only environment on a single device, is it?

**Comment by sublee** [comment]
You understood correctly. torchgpipe does not have a responsibility on multi-node environments.

**Comment by HuYang719** [comment]
Thank you very much!
