### ISSUE TITLE
To utilized torchgpipe into normal double convolution UNet

### ISSUE THREAD

**Issue by yoonguusong** [kakaobrain/torchgpipe#34]
in the code "https://github.com/kakaobrain/torchgpipe/blob/master/benchmarks/unet-memory/main.py",

Unet(B,C) is determined as saying "B stands for the number of convolution blocks in between down sampling layers"

to apply this torchgpipe as the normal Unet which has double convolution,

can we just set B=2 for pipeline parallelism?

**Comment by chiheonk** [comment]
B=2 would be similar to the original UNet, but not exactly same. 
Under the purpose of benchmarking, our version of UNet is somewhat simplified version (no cropping, use Conv3x3 with padding=1, etc.).

Here is the code where our version of UNet is defined. 
https://github.com/kakaobrain/torchgpipe/blob/a1b4ee25574864e7650e7905a69ce156da9752ec/benchmarks/models/unet/__init__.py#L72-L148

You may modify the model as you want, as long as the model is **sequential** and being careful about the usage of `PopCat` module which takes care of long skip connections.

For further understanding of the skip connection mechanism, see the [User Guide](https://torchgpipe.readthedocs.io/en/stable/guide.html#long-skip-connections).

If you have any further question, please feel free to open the issue again :)
