### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by rudvlf0413** [kakaobrain/torchgpipe#4]
In the documentation (guide.rst),
I found a very trivial typo.

`mode = GPipe(model,
             balance=[1, 1, 1, 1],
             devices=[4, 5, 6, 7],  # Specify GPUs.
             chunks=8)
`

should be changed to

`model = GPipe(model,
             balance=[1, 1, 1, 1],
             devices=[4, 5, 6, 7],  # Specify GPUs.
             chunks=8)
`

i.e. the variable name 'mode' should be changed to 'model'.

**Comment by sublee** [comment]
I fixed it. Thanks for reporting.
