### ISSUE TITLE
Not sure if the backpropagation here also follows pipeline

### ISSUE THREAD

**Issue by lynex** [kakaobrain/torchgpipe#5]
Cool project!
In the code, it uses queuing mechanisms to ensure the pipeline in forward propagation. But what I am not sure how it ensures the pipeline during backward propagation. If there is some mechanism, maybe you want to include it in the document.

**Comment by sublee** [comment]
That's a good question.

Backpropagation is performed by PyTorch's autograd engine automatically. We don't need to reimplement backpropagation. The only thing what we should care is to generate an autograd function graph with the correct dependency. A graph generated from `GPipe.forward()` looks like:

```
                 +-- [0][0] -- [1][0] --+
                 |                      |
input -- chunk --+                      +-- cat -- output
                 |                      |
                 +-- [0][1] -- [1][1] --+

* [i][j]: j-th micro-batch on i-th partition
```

The engine uses a thread for each device; 1 for CPU, n more for GPUs. In the case of the above example, `cat`, `[1][0]`, and `[1][1]` are handled on the thread for `cuda:1` while `chunk`, `[0][0]`, and `[0][1]` are handled on the thread for `cuda:0`. Each thread can compute parallelly even though another thread is still computing. Therefore, the pipeline can be ensured during backpropagation:

```
cycle  cuda:0  cuda:1
-----  ------  ------
    1          output
    2          cat
    3          [1][1]
    4  [0][1]  [1][0]
    5  [0][0]
    6  chunk
    7  input
```

The implementation detail is not a spec. It might be changed for more efficiency. So I don't want to introduce it in the "Read the Docs" documentation. Instead, maybe we can write some article or a technical report. We already wrote [an article in our blog](https://kakaobrain.com/blog/66) but currently, it's written in only Korean.

**Comment by sublee** [comment]
@lynex May I close this issue?

**Comment by anxuthu** [comment]
> @anxuthu I don't understand why you think the backpropagation does not follow GPipe. Can you explain it?

I was just not sure why the backpropagation would follow GPipe by making dependencies of micro-batches during the forward process. But I get it now :)

**Comment by sublee** [comment]
@anxuthu Thank you for the update.
