### ISSUE TITLE
Hello,  does it work for a detection network with branches?

### ISSUE THREAD

**Issue by yangpc615** [kakaobrain/torchgpipe#6]
Must be the network of the sequence structure?

` model = cast(nn.Sequential, model)
        model = GPipe(model, balance, devices=devices, chunks=chunks)`

**Comment by sublee** [comment]
Yes, torchgpipe supports only `nn.Sequential` modules. Users have a responsibility to design a module fitting into `nn.Sequential`.

**Comment by yangpc615** [comment]
OK， Thank you.
