### ISSUE TITLE
 Whether to support multi-machine training ？

### ISSUE THREAD

**Issue by yangpc615** [kakaobrain/torchgpipe#7]
Now， I have  two machine with two GPUS, and I want to use them to train a large model,  Can it be  reached by torchgpipe ?

**Comment by sublee** [comment]
Currently, we don't have plan to support multi node training.

**Comment by eric-haibin-lin** [comment]
Is this still the case?

**Comment by sublee** [comment]
@eric-haibin-lin torchgpipe still does not support pipeline parallelism across multiple hosts.

**Comment by amsword** [comment]
is there any alternative which supports multi-node pipelining?
